- name: set openstack-dashboard-apache to be activated
  shell: echo openstack-dashboard-apache horizon/activate_vhost boolean true |debconf-set-selections
  
- name: set openstack-dashboard-apache-ssl to be activated
  shell: echo openstack-dashboard-apache horizon/use_ssl boolean true |debconf-set-selections

- name: ensure horizon packages are installed
  apt: name={{ item }}
  loop:
    - apache2
    - libapache2-mod-wsgi-py3
    - openstack-dashboard-apache

- name: ensure default virtualhost is disabled
  command: a2dissite {{ item }}
  loop:
    - 000-default
    - default-ssl
  notify: restart web services

- name: configure local_settings.py
  template:
    src: etc/openstack-dashboard/local_settings.py
    dest: /etc/openstack-dashboard/local_settings.py
    owner: root
    group: root
    mode: 0644
  notify: restart web services

- name: ensure openstack-dashboard-ssl virtualhost is enabled
  command: a2ensite {{ item }}
  loop:
    - openstack-dashboard-ssl
    - openstack-dashboard-ssl-redirect
  notify: restart web services
  
- name: ensure ssl, wsgi and rewrite modules are enabled
  apache2_module: name={{ item }} state=present
  loop:
    - wsgi
    - ssl
    - rewrite
  notify: restart web services

