- name: ensure tgt,lvm2 and thin-provisioning-tools packages are installed
  apt: name={{ item }}
  loop:
    - lvm2
    - tgt
    - thin-provisioning-tools

- name: create group volume
  lvg: vg=cinder-volumes pvs=/dev/{{ cinder_physical_device }} vg_options=--force

# Modify properly when the host is using LVM for OS
- name: configure LVM to scan only the associated physical device
  replace:
    path: /etc/lvm/lvm.conf
    after: 'This configuration option has an automatic default value.'
    regexp: '(\s+)\# filter = \[ "a\|\.\*\/\|" \](\s+.*)?$'
    replace: 'filter = ["a/{{ cinder_physical_device }}/", "r/.*/"]'

- name: install cinder-volume package
  apt: name=cinder-volume

- name: ensure cinder_api database connections is configured
  ini_file:
    path: /etc/cinder/cinder.conf
    section: database
    option: connection
    value: mysql+pymysql://cinder:{{ cinder_db_password }}@{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}/cinder
  notify: 
  - restart cinder-services

- name: set default section options
  ini_file:
    path: /etc/cinder/cinder.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "transport_url", value: 'rabbit://{{ rabbit_user }}:{{ rabbit_password }}@{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5672/'}
    - { option: "my_ip", value: '{{ internal_ip }}' }
    - { option: "auth_strategy", value: keystone }
    - { option: "enabled_backends", value: lvm }
    - { option: "glance_api_servers", value: 'http://{{ hostvars[groups["storage_nodes"][0]]["internal_ip"] }}:9292' }
  notify: 
  - restart cinder-services

- name: configure keystone_authtoken section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "auth_url", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "memcached_servers", value: '{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: cinder}
    - { option: "password", value: "{{ cinder_identity_password }}" }
    #- { option: "region", value: "{{ region }}" }    
    #- { option: "region_name", value: "{{ region }}" }    
  notify: 
  - restart cinder-services

- name: configure lvm section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: lvm
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "volume_driver", value: cinder.volume.drivers.lvm.LVMVolumeDriver }
    - { option: "volume_group", value: cinder-volumes }
    - { option: "target_protocol", value: iscsi }
    - { option: "target_helper", value: tgtadm }
  notify: 
  - restart cinder-services

- name: Configure line `include /var/lib/cinder/volumes` in file /etc/tgt/targets.conf
  lineinfile:
    path: /etc/tgt/targets.conf
    line: 'include /var/lib/cinder/volumes'
  notify:
  - restart cinder-services

- name: configure oslo_concurrency section
  ini_file:
    path: /etc/cinder/cinder.conf
    section: oslo_concurrency
    option: lock_path
    value: /var/lib/cinder/tmp
  notify:
  - restart cinder-services
