---

# - hosts: all
#   roles:
#     - role: common

# - hosts: controller-nodes
#   roles:
#     - role: dbserver

# - hosts: controller-nodes
#   roles:
#     - role: rabbitserver

# - hosts: controller-nodes
#   roles:
#     - role: keystoneserver

# - hosts: controller-nodes
#   roles:
#     - role: keystone_population
      
# - hosts: storage-nodes
#   roles: 
#     - role: glanceserver

# - hosts: storage-nodes
#   roles: 
#     - role: glance_init

# - hosts: controller-nodes
#   roles:
#     - role: novaserver

# - hosts: controller-nodes
#   roles:
#     - role: nova_init

# - hosts: compute-nodes
#   roles:
#     - role: novacompute

# - hosts: controller-nodes
#   roles:
#     - role: neutronserver

- hosts: network-nodes
  roles:
    - role: networking

- hosts: network-nodes
  roles:
    - role: openvswitch

- hosts: controller-nodes
  roles:
    - role: horizon

# - hosts: compute-nodes
#   roles:
#     - role: controller

# - hosts: network-nodes
#   roles:
#     - role: controller