## Inject password root

- name: configure inject password root
  ini_file:
    path: /etc/nova/nova.conf
    section: libvirt
    option: inject_password
    value: 'true'
  notify:
  - restart nova-services