- name: ensure neutron plugins are installed
  apt: name={{ item }}
  loop:
    #- neutron-server
    #- neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    #- neutron-dhcp-agent
    #- neutron-metadata-agent

- name: ensure neutron database connections is configured
  ini_file:
    path: /etc/neutron/neutron.conf
    section: database
    option: connection
    value: mysql+pymysql://neutron:{{ neutron_db_password }}@{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}/neutron
  notify: 
  - restart neutron-services

- name: set default section options
  ini_file:
    path: /etc/neutron/neutron.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "transport_url",
    value: 'rabbit://{{ rabbit_user }}:{{ rabbit_password }}@{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5672/'}
    - { option: "core_plugin", value: ml2 }
    - { option: "service_plugins", value: router }
    - { option: "allow_overlapping_ips", value: "true" }
    - { option: "notify_nova_on_port_status_changes", value: "true" }
    - { option: "notify_nova_on_port_data_changes", value: "true" }
    - { option: "auth_strategy", value: keystone }
  notify: 
  - restart neutron-services

- name: unset interface_driver option
  ini_file:
    path: /etc/neutron/neutron.conf
    section: DEFAULT
    option: "interface_driver"
    state: absent
  notify:
  - restart neutron-services

- name: configure keystone_authtoken section
  ini_file:
    path: /etc/neutron/neutron.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "auth_url", value: 'http://{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:5000' }
    - { option: "memcached_servers", value: '{{ hostvars[groups["controller_nodes"][0]]["internal_ip"] }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: neutron}
    - { option: "password", value: "{{ neutron_identity_password }}" }
    #- { option: "region", value: "{{ region }}" }    
    - { option: "region_name", value: "{{ region }}" }
    #- { option: "service_token_roles_required", value: "true" }
  notify: 
  - restart neutron-services

########
# Linux Bridge
########

- name: configure the Linux bridge agent. linux_bridge section
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    section: linux_bridge
    option: "physical_interface_mappings"
    value: "provider:{{ external_interface }}"
  notify:
  - restart neutron-services
    
- name: configure the Linux bridge agent. vxlan section
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    section: vxlan
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "enable_vxlan", value: "true" }
    - { option: "local_ip", value: "{{ internal_ip }}" }
    - { option: "l2_population", value: "true" }
  notify:
  - restart neutron-services

- name: configure the Linux bridge agent. securitygroup section
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    section: securitygroup
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "enable_security_group", value: "true" }
    - { option: "firewall_driver", value: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver }
  notify:
  - restart neutron-services

########
# Layer-3
########


- name: configure the layer 3 agent
  ini_file:
    path: /etc/neutron/l3_agent.ini
    section: DEFAULT
    option: "interface_driver"
    value: linuxbridge
  notify:
  - restart neutron-services
    
# Needed when /proc/sys/net/bridge is missing
- name: load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
    
- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    reload: yes

- name: set net.bridge.bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    reload: yes