- name: Ensure etcd is installed
  apt: name=etcd

- name: Ensure etcd config is present
  template:
    src: etc/default/etcd
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: 0664
  notify: restart etcd