- name: ensure keystone ldap connections is configured
  ini_file:
    path: /etc/keystone/keystone.conf
    section: identity
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "domain_config_dir", value: '/etc/keystone/domains' }
    - { option: "domain_specific_drivers_enabled", value: 'True' }
  notify: restart keystone 
 

- name: ensure ldap configuration is updated
  file:
    src: keystone.iesgn.conf
    dest: /etc/keystone/domains/keystone.iesgn.conf
    owner: keystone
    group: keystone
    mode: 0644
  notify: restart keystone    

  