- name: ensure keystone ldap connections is configured
  ini_file:
    path: /etc/keystone/keystone.conf
    section: identity
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "driver", value: "sql"}
    - { option: "domain_config_dir", value: '/etc/keystone/domains' }
    - { option: "domain_specific_drivers_enabled", value: "true" }
  notify: restart keystone 
 
- name: create directory domain
  file:
    path: /etc/keystone/domains
    state: directory
    mode: '0755'

- name: ensure ldap configuration is updated
  template:
    src: keystone.iesgn.conf
    dest: /etc/keystone/domains/keystone.iesgn.conf
    owner: keystone
    group: keystone
    mode: 0644
  notify: restart keystone    

- name: verify if iesgn domain is created
  environment: '{{k3}}'
  command: /usr/bin/openstack domain show iesgn
  register: result
  ignore_errors: True

- name: ensure iesgn domaint is created
  environment: '{{k3}}'
  command: /usr/bin/openstack domain create iesgn
  when: result is failed


## Logo

- name: Copy file with owner and permissions
  copy:
    src: logo-splash2.svg
    dest: /var/lib/openstack-dashboard/static/dashboard/img/logo-splash.svg
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2

## Inject password root

- name: configure inject password root
  ini_file:
    path: /etc/nova/nova.conf
    section: libvirt
    option: inject_password
    value: 'true'
  notify:
  - restart nova-services

## max instancias por host

- name: configure inject password root
  ini_file:
    path: /etc/nova/nova.conf
    section: filter_scheduler
    option: max_instances_per_host
    value: '100'
  notify:
  - restart nova-services

## Allocation ratios

- name: Configure Allocation ratios
  ini_file:
    path: /etc/nova/nova.conf
    section: DEAFULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "cpu_allocation_ratio", value: '16' }
    - { option: "ram_allocation_ratio", value: '1.5' }
    - { option: "disk_allocation_ratio", value: '1.2'}
  notify:
  - restart nova-compute

