- name: ensure keystone ldap connections is configured
  ini_file:
    path: /etc/keystone/keystone.conf
    section: identity
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "driver", value: "sql"}
    - { option: "domain_config_dir", value: '/etc/keystone/domains' }
    - { option: "domain_specific_drivers_enabled", value: "true" }
  notify: restart keystone 
 
- name: create directory domain
  file:
    path: /etc/keystone/domains
    state: directory
    mode: '0755'

- name: ensure ldap configuration is updated
  template:
    src: keystone.iesgn.conf
    dest: /etc/keystone/domains/keystone.iesgn.conf
    owner: keystone
    group: keystone
    mode: 0644
  notify: restart keystone    

- name: verify if iesgn domain is created
  environment: '{{k3}}'
  command: /usr/bin/openstack domain show iesgn
  register: result
  ignore_errors: True

- name: ensure iesgn domaint is created
  environment: '{{k3}}'
  command: /usr/bin/openstack domain create iesgn
  when: result is failed


## Logo

- name: Copy file with owner and permissions
  copy:
    src: logo-splash2.svg
    dest: /usr/share/openstack-dashboard/openstack_dashboard/static/dashboard/img/logo-splash.svg
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2