- name: ensure nova-compute is installed 
  apt: name=nova-compute
  
- name: set default section options
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "transport_url",
    value: 'rabbit://{{ rabbit_user }}:{{ rabbit_password }}@{{ hostvars["controller"]["internal_ip"] }}:5672/'}
    - { option: "my_ip", value: "{{ internal_ip }}" }
  #  - { option: "use_neutron", value: true }
  #  - { option: "firewall_driver", value: nova.virt.firewall.NoopFirewallDriver }
  notify: 
  - restart nova-compute

- name: configure keystone_authtoken section
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ hostvars["controller"]["internal_ip"] }}:5000/' }
    - { option: "auth_url", value: 'http://{{ hostvars["controller"]["internal_ip"] }}:5000/' }
    - { option: "memcached_servers", value: '{{ hostvars["controller"]["internal_ip"] }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: nova}
    - { option: "password", value: "{{ nova_identity_password }}" }
    - { option: "region", value: "{{ region }}" }    
    - { option: "region_name", value: "{{ region }}" }    
  notify: 
  - restart nova-compute

- name: ensure auth_strategy is set to keystone
  ini_file:
    path: /etc/nova/nova.conf
    section: api
    option: auth_strategy
    value: keystone
  notify:
  - restart nova-compute

- name: configure spice section
  ini_file:
    path: /etc/nova/nova.conf
    section: spice
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "enabled", value: true }
    - { option: "server_listen", value: '$my_ip' }
    - { option: "server_proxyclient_address", value: '$my_ip' }
    - { option: "html5proxy_base_url", value: "http://{{ controller_fqdn }}:6082/spice_auto.html" }
    - { option: "html5proxy_host", value: "0.0.0.0" }
    - { option: "html5proxy_port", value: "6082" }
  notify:
  - restart nova-compute

- name: configure glance section
  ini_file:
    path: /etc/nova/nova.conf
    section: glance
    option: api_servers
    value: 'http://{{ hostvars["controller"]["internal_ip"] }}:9292'
  notify:
  - restart nova-compute

- name: configure oslo_concurrency section
  ini_file:
    path: /etc/nova/nova.conf
    section: oslo_concurrency
    option: lock_path
    value: /var/lib/nova/tmp
  notify:
  - restart nova-compute

- name: configure placement section
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "auth_url", value: 'http://{{ hostvars["controller"]["internal_ip"] }}:5000/v3' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: placement}
    - { option: "password", value: "{{ placement_identity_password }}" }
    - { option: "region", value: "{{ region }}" }    
    - { option: "region_name", value: "{{ region }}" }    
  notify: 
  - restart nova-compute

- name: configure neutron section
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "auth_url", value: 'http://{{ hostvars["controller"]["internal_ip"] }}:5000' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: neutron}
    - { option: "password", value: "{{ neutron_identity_password }}" }
    - { option: "region", value: "{{ region }}" }
    - { option: "region_name", value: "{{ region }}" }
  notify:
  - restart nova-compute
